(async()=>{'use strict';
const raw=window.__CATS_BOOK__||await (async()=>{if(window.B){const bin=atob(window.B),u=Uint8Array.from(bin,c=>c.charCodeAt(0)),stream=new Blob([u]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text())}const get=async u=>fetch(u,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('Falha ao carregar conteúdo: '+r.status+' '+u);return r.json()});const [meta,...chunks]=await Promise.all(['/book/meta.json',...Array.from({length:8},(_,i)=>'/book/pages-'+String(i+1).padStart(2,'0')+'.json')].map(get));return {...meta,pages:chunks.flat()}})();
const classify=x=>{const s=String(x||'').trim(),u=s.toLocaleUpperCase('pt-BR');if(/^CAPÍTULO\s+\d+/.test(u))return {t:'chapter',x:s};if(/^REFERÊNCIAS? PRINCIPAIS?:/i.test(s))return {t:'ref',x:s};if(/^\d+\.\s+/.test(s))return {t:'sub',x:s};if(/^[A-ZÁÀÃÂÉÊÍÓÔÕÚÇ0-9 —–-]{4,}$/.test(s)&&s===u)return {t:'section',x:s};if(/^[•▪◦]\s*/.test(s))return {t:'bullet',x:s.replace(/^[•▪◦]\s*/,'')};return {t:'p',x:s}};
const meta=raw.meta||raw, parts0=raw.parts||meta.parts||[], chapters0=raw.chapters||meta.chapters||[];
const mapPart=a=>Array.isArray(a)?{n:a[0],page:a[1],title:a[2]}:{n:a.n??a.number,page:a.page,title:a.title};
const mapChapter=a=>Array.isArray(a)?{n:a[0],page:a[1],title:a[2]}:{n:a.n??a.number,page:a.page,title:a.title};
const BOOK={title:raw.title||meta.title||'Manual do Participante CATS',edition:raw.edition||meta.edition||'DS1 • 2026',parts:parts0.map(mapPart),chapters:chapters0.map(mapChapter),pages:raw.pages.map(a=>({n:a[0],part:a[1],partTitle:a[2],ch:a[3],chTitle:a[4],blocks:(a[5]||[]).map(b=>Array.isArray(b)?{t:b[0],x:b[1]}:classify(b))}))};
const TOTAL=BOOK.pages.length, COVER='data:image/webp;base64,'+(window.C||'');
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let page=1,mode='book',double=false,busy=false,speaking=false;
const saved=(()=>{try{return JSON.parse(localStorage.getItem('catsBookProgress')||'{}')}catch{return {}}})();
const hashPage=()=>{let m=location.hash.match(/p=(\d+)/);return m?+m[1]:null};
page=Math.min(TOTAL,Math.max(1,hashPage()||saved.page||1)); mode=saved.mode||'book';
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('on'),1900)}
function save(){try{localStorage.setItem('catsBookProgress',JSON.stringify({page,mode,updatedAt:Date.now()}))}catch{};history.replaceState(null,'','#p='+page)}
function pageBlock(b){if(b.t==='section')return `<div class="section">${esc(b.x)}</div>`;if(b.t==='sub')return `<div class="sub">${esc(b.x)}</div>`;if(b.t==='bullet')return `<div class="bullet"><span>${esc(b.x)}</span></div>`;if(b.t==='ref')return `<p class="ref">${esc(b.x)}</p>`;if(b.t==='chapter')return `<div class="kicker">${esc(b.x)}</div>`;return `<p>${esc(b.x)}</p>`}
function enhancement(n){
if(n===6)return `<div class="enh"><h3>Mapa do manual</h3><div class="flow"><span class="chip">Fenômeno</span><span class="arrow">→</span><span class="chip">Ocorrência</span><span class="arrow">→</span><span class="chip">Abordagem</span><span class="arrow">→</span><span class="chip">Tática</span><span class="arrow">→</span><span class="chip">Contextos</span><span class="arrow">→</span><span class="chip">Pós-crise</span><span class="arrow">→</span><span class="chip">Integração</span></div></div>`;
if(n===29)return `<div class="enh"><h3>Leitura dinâmica da crise</h3><div class="vizgrid"><div class="vizcard warn"><strong>Dor psicológica</strong><span>Compreender o sofrimento percebido sem reduzi-lo a uma causa única.</span></div><div class="vizcard"><strong>Ambivalência</strong><span>Desejos contraditórios podem coexistir e mudar ao longo da interação.</span></div><div class="vizcard"><strong>Desesperança</strong><span>Explorar alternativas e próximos passos sem promessas ou simplificações.</span></div><div class="vizcard"><strong>Constrição</strong><span>Redução de alternativas percebidas exige tempo, comunicação e reavaliação.</span></div></div></div>`;
if(n===36)return `<div class="enh"><h3>Avaliação não é soma de pontos</h3><div class="vizsplit"><div class="vizcard warn"><strong>Contextualizar</strong><span>Histórico • comportamento presente • método • ambiente • mudanças recentes.</span></div><div class="vizcard good"><strong>Procurar recursos</strong><span>Vínculos • proteção acessível • rede • cooperação • alternativas concretas.</span></div></div></div>`;
if(n===54)return `<div class="enh"><h3>Sistema ATS — leitura de processo</h3><div class="flow"><span class="chip">Acionamento</span><span class="arrow">→</span><span class="chip">Deslocamento</span><span class="arrow">→</span><span class="chip">Estabelecimento</span><span class="arrow">→</span><span class="chip">Avaliação</span><span class="arrow">→</span><span class="chip">Abordagem</span><span class="arrow">→</span><span class="chip">Transição</span></div></div>`;
if(n===106)return `<div class="enh"><h3>Áudio CATS — perguntas e diálogo</h3><audio controls preload="none" src="https://raw.githubusercontent.com/ricmurtapsicologia/Curso-ATS/main/audio/n2/e2-04-perguntas-e-dialogo.mp3"></audio></div>`;
if(n===145)return `<div class="enh"><h3>Transição tática — decisão coordenada</h3><div class="cycle"><span class="chip">Sinal de mudança</span><span class="arrow">→</span><span class="chip">Reavaliar</span><span class="arrow">→</span><span class="chip">Decidir</span><span class="arrow">→</span><span class="chip">Preparar</span></div></div>`;
if(n===203)return `<div class="enh"><h3>Comunicação responsável</h3><div class="vizsplit"><div class="vizcard warn"><strong>Evitar</strong><span>Sensacionalismo, detalhamento de método, romantização e causalidade simplista.</span></div><div class="vizcard good"><strong>Favorecer</strong><span>Alternativas, enfrentamento, ajuda disponível, privacidade e contexto responsável.</span></div></div><div style="margin-top:10px"><iframe loading="lazy" title="Vídeo complementar" src="https://www.youtube-nocookie.com/embed/Fy7n8SfwS_A" allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div></div>`;
if(n===208)return `<div class="enh"><h3>Primeiros Socorros Psicológicos</h3><div class="flow"><span class="chip">PREPARAR</span><span class="arrow">→</span><span class="chip">OLHAR</span><span class="arrow">→</span><span class="chip">ESCUTAR</span><span class="arrow">→</span><span class="chip">CONECTAR</span></div></div>`;
if(n===232)return `<div class="enh"><h3>Sistema ATS — integração final</h3><div class="cycle"><span class="chip">Observar</span><span class="arrow">→</span><span class="chip">Explicar</span><span class="arrow">→</span><span class="chip">Decidir</span><span class="arrow">→</span><span class="chip">Comunicar</span><span class="arrow">→</span><span class="chip">Agir</span><span class="arrow">→</span><span class="chip">Reavaliar</span></div></div>`;
return ''}
function pageHtml(p,side='single',scroll=false){const cls=scroll?'scrollpage':'page';if(p.n===1)return `<article id="s1" class="${cls} cover ${side}"><img alt="Capa oficial do Manual do Participante CATS" src="${COVER}"></article>`;let body=p.blocks.map(pageBlock).join('');return `<article id="s${p.n}" class="${cls} ${side}"><div class="running"><span>${p.part?`Parte ${p.part} • ${esc(p.partTitle)}`:'CATS • Manual do Participante'}</span><span>${p.ch?`Cap. ${p.ch}`:'2026'}</span></div><div class="kicker">${p.ch?`CAPÍTULO ${p.ch}`:'CATS'}</div><h2>${esc(p.chTitle)}</h2>${enhancement(p.n)}${body}<div class="pageno">${p.n}</div></article>`}
function responsive(){double=matchMedia('(min-width:980px)').matches;if(double&&page>1&&page%2===1)page--}
function norm(n){n=Math.min(TOTAL,Math.max(1,n));if(double&&n>1&&n%2===1)n--;return n}
function render(){page=norm(page);const spread=$('#spread');if(page===1||!double)spread.innerHTML=pageHtml(BOOK.pages[page-1],'single');else spread.innerHTML=pageHtml(BOOK.pages[page-1],'left')+(page<TOTAL?pageHtml(BOOK.pages[page],'right'):'');$('#count').textContent=(double&&page>1?`${page}–${Math.min(TOTAL,page+1)}`:`${page}`)+' / '+TOTAL;$('#goto').value=page;$('#prev').disabled=page<=1;$('#next').disabled=(double&&page>1?page+1>=TOTAL:page>=TOTAL);$('#progress').style.width=Math.max(1,page/TOTAL*100)+'%';save()}
function turn(dir){if(busy||mode!=='book')return;const step=double&&page>1?2:1;const target=page+(dir==='next'?step:-step);if(target<1||target>TOTAL)return;busy=true;let el=dir==='next'?$('#spread .right,#spread .single'):$('#spread .left,#spread .single');if(el)el.classList.add(dir==='next'?'turn-next':'turn-prev');setTimeout(()=>{page=target;render();busy=false},260)}
function gotoPage(n){page=norm(+n||1);closeDrawers();if(mode==='scroll'){buildScroll();requestAnimationFrame(()=>$('#s'+page)?.scrollIntoView({behavior:'smooth',block:'start'}));save()}else render()}
function buildToc(){let h='';for(const part of BOOK.parts){h+=`<button class="part" data-p="${part.page}"><span>Parte ${part.n} — ${esc(part.title)}</span><small>${part.page}</small></button>`;const next=(BOOK.parts.find(x=>x.n===part.n+1)||{page:999}).page;for(const c of BOOK.chapters.filter(c=>c.page>=part.page&&c.page<next))h+=`<button data-p="${c.page}"><span>Cap. ${c.n} — ${esc(c.title)}</span><small>${c.page}</small></button>`}$('#toc').innerHTML=h;$$('#toc [data-p]').forEach(b=>b.onclick=()=>gotoPage(b.dataset.p))}
function search(q){q=q.trim().toLocaleLowerCase('pt-BR');if(q.length<2){$('#hits').innerHTML='<p style="padding:16px;color:#647374">Digite pelo menos 2 caracteres.</p>';return}const out=[];for(const p of BOOK.pages){const t=[p.chTitle,...p.blocks.map(b=>b.x)].join(' '),low=t.toLocaleLowerCase('pt-BR'),i=low.indexOf(q);if(i>=0)out.push({n:p.n,title:p.chTitle,snip:t.slice(Math.max(0,i-75),i+170)});if(out.length>=60)break}$('#hits').innerHTML=out.length?out.map(x=>`<button data-h="${x.n}"><b>P. ${x.n} • ${esc(x.title)}</b><p>${esc(x.snip)}…</p></button>`).join(''):'<p style="padding:16px;color:#647374">Nenhum resultado.</p>';$$('#hits [data-h]').forEach(b=>b.onclick=()=>gotoPage(b.dataset.h))}
function buildScroll(){const el=$('#scroll');if(el.dataset.built)return;el.innerHTML=BOOK.pages.map(p=>pageHtml(p,'single',true)).join('');el.dataset.built='1';const obs=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting&&e.intersectionRatio>.45){const n=+(e.target.id.slice(1));if(n){page=n;$('#progress').style.width=Math.max(1,page/TOTAL*100)+'%';save()}}}},{threshold:[.5]});$$('#scroll .scrollpage').forEach(x=>obs.observe(x))}
function setMode(m){mode=m;if(m==='scroll'){buildScroll();$('#workspace').classList.add('hidden');$('#nav').classList.add('hidden');$('#scroll').classList.add('on');$('#scrollB').classList.add('active');$('#bookB').classList.remove('active');setTimeout(()=>$('#s'+page)?.scrollIntoView({block:'start'}),30)}else{$('#workspace').classList.remove('hidden');$('#nav').classList.remove('hidden');$('#scroll').classList.remove('on');$('#bookB').classList.add('active');$('#scrollB').classList.remove('active');render()}save()}
function openDrawer(id){$('#'+id).classList.add('on');setTimeout(()=>$('#'+id+' input')?.focus(),100)}function closeDrawers(){$$('.drawer').forEach(d=>d.classList.remove('on'));if(document.activeElement&&document.activeElement.matches('input'))document.activeElement.blur()}
function tts(){if(!('speechSynthesis'in window)){toast('Leitura em voz alta indisponível neste navegador.');return}if(speaking){speechSynthesis.cancel();speaking=false;toast('Leitura interrompida.');return}const p=BOOK.pages[page-1];const text=[p.chTitle,...p.blocks.filter(b=>!['ref','chapter'].includes(b.t)).map(b=>b.x)].join('. ').slice(0,12000);const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.96;u.onend=()=>speaking=false;speechSynthesis.cancel();speechSynthesis.speak(u);speaking=true;toast('Leitura em voz alta iniciada. Toque novamente para parar.')}
function bind(){
 $('#prev').onclick=()=>turn('prev');$('#next').onclick=()=>turn('next');$('#tocB').onclick=()=>openDrawer('tocD');$('#searchB').onclick=()=>openDrawer('searchD');$('#speakB').onclick=tts;$('#bookB').onclick=()=>setMode('book');$('#scrollB').onclick=()=>setMode('scroll');$('#goto').onchange=e=>gotoPage(e.target.value);$('#q').oninput=e=>search(e.target.value);$$('[data-close]').forEach(x=>x.onclick=closeDrawers);$$('.shade').forEach(x=>x.onclick=closeDrawers);
 let x0=null;$('#stage').addEventListener('pointerdown',e=>x0=e.clientX);$('#stage').addEventListener('pointerup',e=>{if(x0==null)return;const d=e.clientX-x0;x0=null;if(Math.abs(d)>60)turn(d<0?'next':'prev')});
 addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.key==='ArrowRight'||e.key==='PageDown')turn('next');if(e.key==='ArrowLeft'||e.key==='PageUp')turn('prev');if(e.key==='Escape')closeDrawers();if(e.key==='/' ){e.preventDefault();openDrawer('searchD')}});
 addEventListener('hashchange',()=>{const n=hashPage();if(n&&n!==page)gotoPage(n)});matchMedia('(min-width:980px)').addEventListener('change',()=>{responsive();if(mode==='book')render()});
}
responsive();buildToc();bind();setMode(mode);setTimeout(()=>toast('Livro digital carregado • 249 páginas'),350);
window.__CATS_TEST__={book:BOOK,getState:()=>({page,mode,double,total:TOTAL}),goto:gotoPage,search};
})().catch(err=>{console.error(err);const s=document.getElementById('spread');if(s)s.innerHTML='<article class="page single"><h2>Falha ao carregar o livro</h2><p>'+String(err.message||err)+'</p></article>'});
